# Generated by Django 4.1.7 on 2023-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
